#
# Copyright (c) 2020 Inceptio Corporation.
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.
#

float32 xo       #float32 x_p                    
float32 yo       #float32 y_h 
float32 zo 

float32 pitch
float32 yaw
float32 roll

float32 vx
float32 vy

float32 gear_pos                       #float32 gearpos                     
float32 eng_trq_nm                    #float32 engtrq_nm               
float32 eng_spd_rpm                   #float32 engspd_rpm 